server:
  port: ${SERVER_PORT}

spring:
  datasource:
    url: jdbc:mysql://${DB_URL}/intern
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6379
      repositories:
        enabled: false

  sql:
    init:
      encoding: UTF-8

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org.springframework.cache: trace

jwt-secret-key: ${JWT_KEY}