server:
  port: ${SERVER_PORT}

spring:
  datasource:
    url: jdbc:mysql://${DB_URL}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      repositories:
        enabled: false

  sql:
    init:
      encoding: UTF-8

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org.springframework.cache: trace

jwt-secret-key: ${JWT_KEY}

firebase:
  credentials:
    path: ${FIREBASE_CREDENTIALS_PATH}
    server-key: ${FIREBASE_SERVER_KEY}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
    default-models-expand-depth: -1
  api-docs:
    path: /v3/api-docs
    enabled: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /users/**
    - /api/v1/notifications/**
    - /v3/api-docs/**
    - /v3/api-docs.yaml
    - /swagger-resources/**
    - /swagger-ui/**
    - /webjars/**
  show-actuator: false
  packages-to-scan: com.donut.swaipe